name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          ls -a
      - name: Checkout GitHub Offical Action
        uses: actions/checkout@v1
      - name: List Files After GitHub Checkout
        run: |
          ls -a
      - name: Simple JS Action Hello World
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Marko
      - name: Log Greeting Time
        run: echo "{{steps.greet.outputs.time}}"